name: Java Service CI

on:
  push:
    paths:
      - "java-service/**"
      - ".github/workflows/java-service.yml"
  pull_request:
    paths:
      - "java-service/**"
      - ".github/workflows/java-service.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check project structure
        run: |
          pwd
          ls -la
          find . -name pom.xml

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build
        working-directory: ./java-service
        run: mvn clean package -DskipTests

      - name: Test
        working-directory: ./java-service
        run: mvn test